language: node_js
services:
  - docker
before_install:
  - docker pull teamspeak
  - sudo apt-get update
  - sudo apt-get install make
  - meke ts
install:
  - npm install
  - npm install --prefix src/frontend
script:
  - npm run test
after_script:
  - docker stop teamspeak
