language: node_js
dist: xenial
os: linux
node_js:
  - 13
  - 12
  - 10
services:
  - docker
  - mongodb
before_install:
  - docker version
  - docker pull teamspeak
  - make ts
cache:
  npm: true
install:
  - make config
  - npm install
  - npm run build:frontend
script:
  - npm run test:backend
  - npm run test:frontend
after_script:
  - docker stop teamspeak
jobs:
  include:
    - stage: deploy
      before_install: skip
      install: skip
      script: skip
      after_script: skip
      before_deploy:
        - npm run install:pages && npm run build:pages
      deploy:
        provider: pages:git
        token: ${GH_TOKEN}
        name: ${GH_NAME}
        email: ${GH_EMAIL}
        local_dir: docs/build/
        edge: true # opt in to dpl v2
