language: node_js
dist: xenial
os: linux
node_js:
  - 13
  - 12
  - 10
services:
  - docker
  - mongodb
before_install:
  - docker version
  - docker pull teamspeak
  - make ts
cache:
  yarn: true
install:
  - make config
  - yarn install
  - yarn run build
script:
  - yarn run test
after_script:
  - docker stop teamspeak
