language: node_js
dist: xenial
os: linux
node_js:
  - 13
  - 12
  - 10
services:
  - docker
  - mongodb
before_install:
  - docker version
  - docker pull teamspeak
  - make ts
cache:
  yarn: true
install:
  - make config
  - yarn install
  - yarn run build
script:
  - yarn run test
after_script:
  - docker stop teamspeak
jobs:
  include:
    - stage: deploy
      before_install: skip
      install: skip
      script: skip
      after_script: skip
      before_deploy:
        - yarn run docs:install && yarn run docs:build
      deploy:
        provider: pages:git
        token: ${GH_TOKEN}
        name: ${GH_NAME}
        email: ${GH_EMAIL}
        local_dir: docs/build/
        edge: true # opt in to dpl v2
