language: node
node_js:
  - 10
  - 12
  - 13
services:
  - docker
before_install:
  - docker pull teamspeak
  - make ts
install:
  - npm install
  - npm install --prefix src/frontend
script:
  - npm run test
  - npm run front:test
after_script:
  - docker stop teamspeak
