# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
        mongodb-version: [4.0, 4.2]
    services:
      docker:
        image: docker
      redis:
        image: redis
        ports:
        - 6379:6379
    steps:
    - uses: actions/checkout@v2
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.2.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: insert-replica-set-name
    - name: Create TeamSpeak server
      run: |
        docker pull teamspeak
        make ts
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create config files
      run: make config
    - name: Install dependencies
      run: yarn install
    - name: Build Client APP
      run: yarn run build
    - name: Test Server
      run: yarn run test:server
      env:
        CI: true
    - name: Test Client
      run: yarn run test:client
      env:
        CI: true
    - name: Stop TeamSpeak container
      run: docker stop teamspeak
